Repository 2023-Summer-Bootcamp-Team-B/GitPractice, pull requests merged in 2023-07, with the labels that each got.

#4 Docs: juwonMakedFile.txt 내용추가
  .idea/workspace.xml
  juwonMakedFile.txt
Labels: 문서

#6 Chore: gitignore 내용추가
  .gitignore
  .idea/workspace.xml
Labels: 리펙토링, 기타/세팅

#9 Feat: 프린트문 작성
  soein2.py
Labels: 기능구현

#11 Docs : 전병선 소개 문서 작성
  mejbs.txt
Labels: 문서

#13 Docs: 깃 연습용 txt 파일 추가
  seoin3.txt
Labels: 문서

#15 전병선이 했떤 게임들
  jbs.py
Labels: 기능구현

#17 깃허브 3번째 시도입니다.
  jbs_test.py
Labels: 테스트

#19 네번째 연습 파이썬 코드 깃 - commit에 [??] 작성 실수
  jbs_4.py
Labels: 기능구현

#21 Docs : txt 파일 연습
  jbs.txt
Labels: 문서
